### ISSUE TITLE
Unable to make kernel module

### ISSUE THREAD

**Issue by testcaoy7** [kristjoc/pep-dna#4]
Failed when generating "tcp_utils.o".

Tested on Debian 10 and Ubuntu 20.04.

I only need TCP function, so I use "./configure --with-localhost" flag.
Maybe RINA and CCN module is mandatory ?

**Comment by kr1stj0n** [comment]
The error is likely due to testing with a newer kernel.
I'm currently in the process of refactoring a significant portion of the code to ensure compatibility with the latest kernel.

Meanwhile, please feel free to test it using the following link: https://github.com/kr1stj0n/LgcShq-RINA/tree/main/pep-dna

**Comment by testcaoy7** [comment]
@kr1stj0n Thank you for the reply. 
I have tested pep-dna in LgcShq-RINA repo and it also ends up with error when generating "tcp_utils.o".

Platform: Ubuntu 20.04
Kernel: 5.4.0-156-generic with linux-headers-5.4.0-156-generic
Flags: ./configure --with-local-sender --with-local-receiver

**Comment by kr1stj0n** [comment]
I am currently testing it in Debian 11 with kernel 5.10.162 and I didn't get any errors while building and compiling it. Can you provide some build and compilation logs?

**Comment by testcaoy7** [comment]
Oddly, kernel module was built on Alpine Linux with 6.1.46-0-virt kernel.

Compiler gave out lots of warning and ended with "Skipping BTF generation for .../pepdna.ko due to unavailability of vmlinux" message. But the .ko module was generated.

Next, "make install" command gave out "SSL error" and "missing 'System.map' file" but the module was installed into the system.

Finally, "modprobe pepdna port=9999 pepdna_mode=0" command gave out "ERROR: could not insert 'pepdna': Invalid argument".

I am installing Debian 11 on my Proxmox machine. I will test it again on Debian 11.

**Comment by kr1stj0n** [comment]
`pepdna_mode` seems to be an old argument.
 
Try `sudo modprobe pepdna port=9999 mode=0`

**Comment by testcaoy7** [comment]
Yes. `modprobe pepdna port=9999 mode=0` worked.
But there must be something wrong with the iptables. I tried to use iperf3 to benchmark but iperf3 reported `unable to receive control message: Connection reset by peer` after applying iptables' rules.

The script I used:
```
#!/bin/bash
iptables -t mangle -I PREROUTING -m mark --mark 333 -m comment --comment pepdna -j CONNMARK --save-mark
iptables -t mangle -I OUTPUT -m connmark --mark 333 -m comment --comment pepdna -j CONNMARK --restore-mark

iptables -t mangle -N DIVERT
iptables -t mangle -A PREROUTING -p tcp -m socket -j DIVERT
iptables -t mangle -A DIVERT -j MARK --set-mark 1
iptables -t mangle -A DIVERT -j ACCEPT

ip rule add fwmark 1 lookup 100
ip route add local 0.0.0.0/0 dev lo table 100
ip rule add fwmark 333 lookup 200
ip route add local 0.0.0.0/0 dev lo table 200

iptables -A PREROUTING -t mangle -i enp6s18 -p tcp --dport 5201 -j TPROXY --on-port 9999 --tproxy-mark 1
```

It's the same script written in TCP-to-TCP tutorial: https://github.com/kr1stj0n/pep-dna/wiki/TCP-to-TCP
Only the ethernet interface name and dport was changed.

Kernel tweak was applied as well:
```
net.ipv4.conf.all.route_localnet=1
net.ipv4.ip_forward=1
net.ipv4.ip_nonlocal_bind=1
net.ipv4.conf.all.forwarding=1
net.ipv4.conf.enp6s18.rp_filter=0
```

I shall tweak iptables when more time is available. Right now I can confirm that the kernel module (from LgcShq repo) can be built on both Alpine Linux with 6.x kernel and Debian 11 with 5.10.x kernel.

**Comment by testcaoy7** [comment]
There could be something wrong with the module.
I got `pepdna_tcp_accept(): con not found in Hash Table` in VNC console of Debian VM.
Maybe the module is loaded but now working ?

**Comment by kr1stj0n** [comment]
What is the scenario that you're trying to test?
3 nodes: sender --- pep --- receiver
2 nodes: sender-pep --- receiver
2 nodes: sender --- pep-receiver

**Comment by testcaoy7** [comment]
2 nodes: sender-pep -- receiver
I use `-R` flag with iperf3, so server is the sender end. 
PEP-DNA is installed on server but not on client.

**Comment by testcaoy7** [comment]
Update:
I loaded a clean installation of Debian 11 on a VPS I rent and built the pepdna.ko from `LgcShq-RINA` repo.
Building flags:  `./configure --with-local-receiver --with-debug`

I am confused because `--with-localhost` was replaced by `--with-local-receiver` and  `--with-local-sender` but the "local-receiver" flag did not throw any warning nor error of any kind when compiling. 
"local-sender" flag, however, gave out a warning. 

First, create a script that loads the module, sets up the routing table and hijacks inbound traffic (with `--dport 5201`) to port 9999.
```
#!/bin/bash
modprobe pepdna port=9999 mode=0

# 1. Save conntrack CONNMARK on packets sent with MARK 333 (PEP-DNA connect)
iptables -t mangle -I PREROUTING -m mark --mark 333 -m comment --comment pepdna -j CONNMARK --save-mark

# 2. Restore MARK on packets belonging to connections with conntrack CONNMARK 333.
iptables -t mangle -I OUTPUT -m connmark --mark 333 -m comment --comment pepdna -j CONNMARK --restore-mark

iptables -t mangle -N DIVERT
iptables -t mangle -A PREROUTING -p tcp -m socket -j DIVERT
iptables -t mangle -A DIVERT -j MARK --set-mark 1
iptables -t mangle -A DIVERT -j ACCEPT

ip rule add fwmark 1 lookup 100
ip route add local 0.0.0.0/0 dev lo table 100
ip rule add fwmark 333 lookup 200
ip route add local 0.0.0.0/0 dev lo table 200

iptables -A PREROUTING -t mangle -p tcp --dport 5201 -j TPROXY --on-port 9999 --tproxy-mark 1
```

Second, make sure that `ip_forward` was enabled. `sysctl net.ipv4.ip_forward`
The outputs should be `net.ipv4.ip_forward = 1`.
(Actually, I created a `90-pep.conf` file in `/etc/sysctl.d` and made `ip_forward = 1` default. I also disabled `rp_filter` by setting its value to 0.)

Before running the script, iperf3 server running on TCP port 5201 should be reachable.
After running the script, iperf3 client reported `iperf3: error - unable to connect to server: Connection timed out.`

Due to enabling of debug flag, check kernel log for any error (`dmesg | grep pepdna`):
```
[ 4143.815942] pepdna[DBG] print_syn(): PEP-DNA intercepted SYN packet destined to 172.16.0.9:5201
[ 4143.817308] pepdna[DBG] pepdna_tcp_nonagle(): Disabling Nagle Algorithm
[ 4143.817313] pepdna[DBG] pepdna_tcp_nodelayedack(): Setting TCP_QUICKACK
[ 4143.817320] pepdna[DBG] pepdna_set_mark(): Marked socket with mark 333
[ 4193.801865] pepdna[ERR] pepdna_tcp_connect(): kernel_connect failed -110
[ 4193.805259] pepdna[DBG] pepdna_con_kref_release(): Cleaning up con. with hash_id 501930126
[ 4210.185201] pepdna[ERR] pepdna_tcp_connect(): kernel_connect failed -110
[ 4210.188583] pepdna[DBG] pepdna_con_kref_release(): Cleaning up con. with hash_id 34482504
[ 4259.335475] pepdna[ERR] pepdna_tcp_connect(): kernel_connect failed -110
[ 4259.338830] pepdna[DBG] pepdna_con_kref_release(): Cleaning up con. with hash_id 302909953
[ 4273.670973] pepdna[ERR] pepdna_tcp_connect(): kernel_connect failed -110
[ 4273.674363] pepdna[DBG] pepdna_con_kref_release(): Cleaning up con. with hash_id 3516483116
```

**Comment by testcaoy7** [comment]
I recompiled module with `./configure --with-local-sender --with-debug`.
After running the script, iperf3 client reports `error - unable to receive control message: Connection reset by peer`.

Kernel log:
```
[  136.722014] pepdna: loading out-of-tree module taints kernel.
[  136.723477] pepdna: module verification failed: signature and/or required key missing - tainting kernel
[  136.726823] pepdna[DBG] pepdna_tcp_nonagle(): Disabling Nagle Algorithm
[  136.726825] pepdna[DBG] pepdna_tcp_nodelayedack(): Setting TCP_QUICKACK
[  136.726840] pepdna[DBG] pepdna_tcp_listen_init(): listener bound to port 9999
[  136.726846] pepdna[DBG] pepdna_tcp_listen_init(): PEPDNA is listening for incoming TCP connections
[  136.726871] pepdna[INFO] pepdna_init(): PEP-DNA LKM loaded succesfully in TCP2TCP mode
[  139.653708] pepdna[DBG] pepdna_tcp_listen_data_ready(): pepdna listen data ready sk 0000000021f5b32d
[  139.654543] pepdna[DBG] pepdna_tcp_listen_data_ready(): pepdna listen data ready sk 00000000059e7ffd
[  139.655122] pepdna[ERR] pepdna_tcp_accept(): con not found in Hash Table
```

**Comment by testcaoy7** [comment]
Finally, I also tried pep-dna from this repo (`/kr1stj0n/pep-dna`) with `./configure --with-localhost --with-debug`.
This time no error nor warnings was given when building.
Unfortunately, kernel module reported that it failed to mark the packets with mark 333.
(I am sorry, I forgot to copy the dmesg log on this one.)

**Comment by kr1stj0n** [comment]
It seems like the errors are related to iptables. I've updated them, but haven't committed yet.

First, you have to make sure that you set up the topology correctly.
If you want the following topology: sender-pep --- receiver, then you have to build pepdna with `--with-local-sender`. In this way, the proxy which is loaded at the sender host will intercept SYN packets going from the sender to the receiver, so you have to run iperf -s at the receiver node and iperf -c at the sender node.

Try the following iptables:

```
load_local_pep_at_sender() {

  CMD="sudo iptables -t mangle -N DIVERT;
  sudo iptables -t mangle -A INPUT -p tcp -m socket -j DIVERT;
  sudo iptables -t mangle -A DIVERT -j MARK --set-mark 1;
  sudo iptables -t mangle -A DIVERT -j ACCEPT;

  sudo ip rule add fwmark 1 lookup 100;
  sudo ip route add local 0.0.0.0/0 dev lo table 100;
  sudo ip rule add fwmark 333 lookup 200;
  sudo ip route add 0.0.0.0/0 dev ${sender_iface} table 200;

  sudo iptables -A OUTPUT -t nat -p tcp -j REDIRECT --to-port 9999 -m mark ! --mark 333"

  ssh $sender_host $CMD

  # Set sysctl variables to allow full transparency
  CMD="sudo sysctl -w net.ipv4.conf.all.route_localnet=1;
  sudo sysctl -w net.ipv4.ip_forward=1;
  sudo sysctl -w net.ipv4.ip_nonlocal_bind=1;
  sudo sysctl -w net.ipv4.conf.all.forwarding=1;
  sudo sysctl -w net.ipv4.conf.lo.rp_filter=0"

  ssh $sender_host $CMD

  # Load PEP-DNA in TCP2TCP mode (Use --with-local-sender)
  echo "Loading local pep-dna at the sender node"
  CMD="sudo modprobe pepdna port=9999 mode=0"
  ssh $client_host $CMD
}
```

**Comment by testcaoy7** [comment]
There is another thing...
After loading the `pepdna` kernel module, the system lost its ipv4 outbound connections.
I still can ssh into the system and do iperf3 benchmark but `curl www.google.com` resulted in timeout as well as other websites.

**Comment by testcaoy7** [comment]
`dmesg` reports `pepdna_tcp_connect(): kernel_connect failed -113`

**Comment by testcaoy7** [comment]
I made a mistake. It appears whoever makes the first connection is the `sender`. I checked `dmesg` logs and using `-R` flag with iperf3 did not trigger PEP-DNA at all. (The benchmark I did above was a mistake and a false positive.)

This time I used two machines with public IP. One located in `Tokyo` and another located in `United States West`.
I ran `iperf3 -s` at US machine. (`receiver` end)
I loaded PEP-DNA in Tokyo machine and ran `iperf3 -c` (`sender` end)
 And iperf3 could not connect to its server. It reports `iperf3: error - unable to send control message: Bad file descriptor.`

dmesg log:
```
[  359.448714] pepdna[INFO] pepdna_init(): PEP-DNA LKM loaded succesfully in TCP2TCP mode
[  382.525996] pepdna[ERR] pepdna_tcp_connect(): kernel_bind -98
[  383.535225] pepdna[ERR] pepdna_tcp_connect(): kernel_bind -98
[  385.551232] pepdna[ERR] pepdna_tcp_connect(): kernel_bind -98
[  389.775245] pepdna[ERR] pepdna_tcp_connect(): kernel_bind -98
[  397.967256] pepdna[ERR] pepdna_tcp_connect(): kernel_bind -98
[  414.095239] pepdna[ERR] pepdna_tcp_connect(): kernel_bind -98
[  446.351216] pepdna[ERR] pepdna_tcp_connect(): kernel_bind -98
[  649.102986] pepdna[ERR] pepdna_tcp_connect(): kernel_connect failed -110
```

**Comment by kr1stj0n** [comment]
Hi,
I see many "errors" in one Github issue which can make things a bit difficult to debug. Can I close this issue, since it was initially related to the kernel module compilation, and open a new one about the pepdna operation in a 2-node topology?
I am testing the same scenario as you, and it seems to work fine.

**Comment by testcaoy7** [comment]
@kr1stj0n Sure. I will close this issue. And I will try again when more time is available to me. Thank you for building such amazing project.
